<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Views\User\" />
    <Folder Include="Areas\CaseManager\Data\" />
    <Folder Include="Areas\CaseManager\Models\" />
    <Folder Include="Areas\Client\Data\" />
    <Folder Include="Areas\Client\Models\" />
  </ItemGroup>
  	<ItemGroup>
		<UpToDateCheckBuilt Include="wwwroot/css/site.css" Set="Css" />
	</ItemGroup>
	<Target Name="Tailwind" BeforeTargets="Build;PrepareForPublish">
		<Exec Command="npm install" />
		<Exec Command="npx @tailwindcss/cli -i ./wwwroot/css/site.css -o ./wwwroot/css/output.css --minify" />
		<ItemGroup>
			<Content Include="wwwroot/css/output.css" CopyToPublishDirectory="Always" />
		</ItemGroup>
	</Target>
	<ItemGroup>
		<Compile Remove="caseManageMentSystem.Tests\**" />
		<Content Remove="caseManageMentSystem.Tests\**" />
		<EmbeddedResource Remove="caseManageMentSystem.Tests\**" />
		<None Remove="caseManageMentSystem.Tests\**" />
	</ItemGroup>

</Project>
